### ISSUE TITLE
Dependency host is down

### ISSUE THREAD

**Issue by AlexandreRio** [freenet/plugin-Freereader#6]
One of the site hosting a dependency (jaxen) is now down. Archive.org provides the right file (the checksums match) but should not be used to host our dependencies.

Temporary solution:
http://web.archive.org/web/20150506002151/http://dist.codehaus.org/jaxen/distributions/jaxen-1.1.1.zip

URL in the build file:
https://github.com/freenet/plugin-Freereader/blob/master/build.xml#L126

**Comment by Bombe** [comment]
The real fix is to use a real dependency management system here. :/

**Comment by Thynix** [comment]
A real dependency management system is certainly the long-term solution, but for fixing the build it may be more than someone is willing to do. I'd be fine with either approach, and will be happy to host this on the project's servers.

**Comment by nextgens** [comment]
The short term solution has been implemented in b15eb36
